### ISSUE TITLE
Chalk screenshots are not used when clicking on the chalk icon

### ISSUE THREAD

**Issue by timkrief** [pebble-dev/rebble-dev-portal#22]
Here's an example of the issue:
![image](https://user-images.githubusercontent.com/14089949/155304053-ab525244-1a36-46e1-a25b-8f7d2839aa3c.png)

**Comment by Willow-Systems** [comment]
Thanks for reporting this @timkrief ! I've just pushed a fix, so once that makes it's way into production you should see the expected behaviour
